classdef BasisTest < matlab.unittest.TestCase
    %BASISTEST Regression tests for the basis constructions.
    %
    %   The reference values in tests/data/basisReference.mat were generated by
    %   the Python implementation (mvBayesPy) and, for the B-spline basis,
    %   directly by patsy.bs. Passing these tests means the MATLAB and Python
    %   implementations agree numerically.
    %
    %   Run with:  results = runtests('tests')      (or the "test" build task)

    properties
        Ref
    end

    properties (Constant)
        Tol = 1e-9
    end

    methods (TestClassSetup)
        function addPackageToPath(testCase)
            % Make the package callable regardless of the working directory.
            here = fileparts(mfilename('fullpath'));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fileparts(here)));
        end

        function loadReference(testCase)
            here = fileparts(mfilename('fullpath'));
            loaded = load(fullfile(here, 'data', 'basisReference.mat'), 'ref');
            testCase.Ref = loaded.ref;
        end
    end

    methods (Test)

        function bsplineMatchesPatsy(testCase)
            % basisBspline reproduces patsy.bs(df=nBasis).' exactly.
            ref = testCase.Ref;
            for i = 1:numel(ref.bspline_basis)
                nMV = ref.bspline_nMV(i);
                nBasis = ref.bspline_nBasis(i);
                expected = ref.bspline_basis{i};
                actual = basisBspline(linspace(0,1,nMV), nBasis);
                testCase.verifyEqual(size(actual), size(expected), ...
                    sprintf('size mismatch for nMV=%d, nBasis=%d', nMV, nBasis));
                testCase.verifyEqual(actual, expected, 'AbsTol', testCase.Tol, ...
                    sprintf('values differ for nMV=%d, nBasis=%d', nMV, nBasis));
            end
        end

        function bsplineSpcolAgreesWithRecursion(testCase)
            % The Curve Fitting Toolbox collocation matrix and the fallback
            % Cox-de Boor recursion must produce the same basis. Skipped when
            % the toolbox is absent, in which case only one path exists.
            testCase.assumeTrue(mvbInternal.curveFittingAvailable(), ...
                'Curve Fitting Toolbox not available; only one path to compare.');
            degree = 3;
            for cfg = [3 4 8 15 20; 99 99 99 99 128]
                nBasis = cfg(1); nMV = cfg(2);
                fDomain = linspace(0, 1, nMV);
                knots = mvbInternal.bsplineKnots(fDomain, nBasis, degree);
                fromToolbox = spcol(knots, degree+1, fDomain);
                fromRecursion = mvbInternal.bsplineDesign(fDomain, knots, degree);
                testCase.verifyEqual(fromToolbox, fromRecursion, 'AbsTol', testCase.Tol, ...
                    sprintf('spcol and the recursion differ for nMV=%d, nBasis=%d', nMV, nBasis));
            end
        end

        function bsplineIsPartitionOfUnity(testCase)
            % Before the intercept column is dropped, a clamped B-spline basis
            % sums to one at every point.
            degree = 3;
            fDomain = linspace(0, 1, 99);
            knots = mvbInternal.bsplineKnots(fDomain, 8, degree);
            if mvbInternal.curveFittingAvailable()
                B = spcol(knots, degree+1, fDomain);
            else
                B = mvbInternal.bsplineDesign(fDomain, knots, degree);
            end
            testCase.verifyEqual(sum(B, 2), ones(numel(fDomain),1), 'AbsTol', 1e-12);
        end

        function bsplineRejectsTooFewBases(testCase)
            testCase.verifyError(@() basisBspline(linspace(0,1,50), 2), ...
                'basisBspline:nBasisTooSmall');
        end

        function legendreMatchesReference(testCase)
            ref = testCase.Ref;
            for i = 1:numel(ref.legendre_basis)
                nMV = ref.legendre_nMV(i);
                nBasis = ref.legendre_nBasis(i);
                expected = ref.legendre_basis{i};
                actual = basisLegendre(linspace(0,1,nMV), nBasis/2, 1);
                testCase.verifyEqual(actual, expected, 'AbsTol', testCase.Tol, ...
                    sprintf('values differ for nMV=%d, nBasis=%d', nMV, nBasis));
            end
        end

        function basisSetupMatchesReference(testCase)
            % Full basisSetup agreement: basis, coefficients, explained
            % variance, truncation error, and projection of new responses.
            ref = testCase.Ref;
            Y = ref.setup_Y;
            Ynew = ref.setup_Ynew;
            for i = 1:numel(ref.setup_basisType)
                basisType = ref.setup_basisType{i};
                nBasisIn = ref.setup_nBasisIn(i);
                if nBasisIn < 0
                    nBasisIn = nan;
                end
                scale = logical(ref.setup_scale(i));
                tag = sprintf('%s (scale=%d)', basisType, scale);

                obj = basisSetup(Y, basisType, [], nBasisIn, 0.99, true, scale);

                testCase.verifyEqual(obj.nBasis, ref.setup_nBasis(i), ...
                    ['nBasis: ' tag]);
                testCase.verifyEqual(obj.propVarExplained, ref.setup_propVarExplained(i), ...
                    'AbsTol', testCase.Tol, ['propVarExplained: ' tag]);
                testCase.verifyEqual(obj.basis, ref.setup_basis{i}, ...
                    'AbsTol', testCase.Tol, ['basis: ' tag]);
                testCase.verifyEqual(obj.coefs, ref.setup_coefs{i}, ...
                    'AbsTol', testCase.Tol, ['coefs: ' tag]);
                testCase.verifyEqual(obj.varExplained(:), ref.setup_varExplained{i}(:), ...
                    'AbsTol', testCase.Tol, ['varExplained: ' tag]);
                testCase.verifyEqual(obj.truncError, ref.setup_truncError{i}, ...
                    'AbsTol', testCase.Tol, ['truncError: ' tag]);
                testCase.verifyEqual(obj.getCoefs(Ynew), ref.setup_coefsNew{i}, ...
                    'AbsTol', testCase.Tol, ['getCoefs: ' tag]);
                testCase.verifyEqual(obj.getYtrunc(Ynew), ref.setup_YtruncNew{i}, ...
                    'AbsTol', testCase.Tol, ['getYtrunc: ' tag]);
            end
        end

        function customBasisMatchesReference(testCase)
            ref = testCase.Ref;
            Y = ref.custom_Y;
            for i = 1:numel(ref.custom_label)
                label = ref.custom_label{i};
                customBasis = ref.custom_customBasis{i};
                basisTransform = ref.custom_basisTransform{i};
                if isempty(basisTransform)
                    basisTransform = [];
                end

                obj = basisSetup(Y, "custom", customBasis, ref.custom_nBasis(i), ...
                    0.99, true, false, 1e-15, basisTransform);

                testCase.verifyEqual(obj.basis, ref.custom_basis{i}, ...
                    'AbsTol', testCase.Tol, ['basis: ' label]);
                testCase.verifyEqual(obj.coefs, ref.custom_coefs{i}, ...
                    'AbsTol', testCase.Tol, ['coefs: ' label]);
                testCase.verifyEqual(obj.varExplained(:), ref.custom_varExplained{i}(:), ...
                    'AbsTol', testCase.Tol, ['varExplained: ' label]);
            end
        end

        function orthonormalCustomBasisPassesThrough(testCase)
            % An already-orthonormal basis is used as given, not re-factored.
            rng(0);
            [Q, ~] = qr(randn(40, 5), 0);
            customBasis = Q.';
            Y = randn(30, 40);
            obj = basisSetup(Y, "custom", customBasis, 5);
            testCase.verifyTrue(isOrthogonal(customBasis));
            testCase.verifyEqual(obj.basis, customBasis, 'AbsTol', 1e-14);
        end

        function nonOrthonormalBasisIsOrthonormalized(testCase)
            customBasis = randn(5, 40);
            Y = randn(30, 40);
            obj = basisSetup(Y, "custom", customBasis, 5);
            testCase.verifyFalse(isOrthogonal(customBasis));
            testCase.verifyTrue(isOrthogonal(obj.basis));
        end

        function legendreOddNBasisRoundsUp(testCase)
            % An odd nBasis is rounded up to the next even number.
            Y = randn(30, 50);
            obj = basisSetup(Y, "legendre", [], 7);
            testCase.verifyEqual(obj.nBasis, 8);
        end

        function bsplineAndLegendreRequireNBasis(testCase)
            Y = randn(30, 50);
            testCase.verifyError(@() basisSetup(Y, "bspline"), 'basisSetup:nBasisRequired');
            testCase.verifyError(@() basisSetup(Y, "legendre"), 'basisSetup:nBasisRequired');
            testCase.verifyError(@() basisSetup(Y, "bspline", [], 2), 'basisSetup:nBasisTooSmall');
            testCase.verifyError(@() basisSetup(Y, "custom"), 'basisSetup:customBasisRequired');
            testCase.verifyError(@() basisSetup(Y, "custom", randn(4, 17)), ...
                'basisSetup:customBasisSize');
        end

    end
end
